import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/db/database.types";
import type { TaskDTO } from "@/types";

const ensureEnv = (name: string, value?: string) => {
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
};

export const supabaseUrl = ensureEnv("SUPABASE_URL", process.env.SUPABASE_URL);
export const supabaseServiceRoleKey = ensureEnv("SUPABASE_KEY", process.env.SUPABASE_KEY);
export const testUserId = ensureEnv("E2E_USERNAME_ID", process.env.E2E_USERNAME_ID);
export const testUserEmail = ensureEnv("E2E_USERNAME", process.env.E2E_USERNAME);
export const testUserPassword = ensureEnv("E2E_PASSWORD", process.env.E2E_PASSWORD);

export const supabaseAdmin = createClient<Database>(supabaseUrl, supabaseServiceRoleKey, {
  auth: { persistSession: false },
});

export const formatIsoDate = (daysAhead: number) => {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + daysAhead);
  return date.toISOString().split("T")[0];
};

export const deleteTask = async (task: TaskDTO | { id: string; user_id: string }) => {
  await supabaseAdmin.from("tasks").delete().eq("id", task.id).eq("user_id", task.user_id);
};

export const getTestUser = async () => {
  const { data, error: userError } = await supabaseAdmin.auth.admin.getUserById(testUserId);
  const user = data?.user;

  if (!user || userError) {
    throw new Error(`Failed to resolve test user: ${userError?.message ?? "unknown error"}`);
  }

  return user;
};

export const createTestTask = async (overrides?: Partial<Database["public"]["Tables"]["tasks"]["Insert"]>) => {
  const user = await getTestUser();

  const testTaskTitle = `E2E Task ${Date.now()}`;
  const { data: createdTask, error: taskError } = await supabaseAdmin
    .from("tasks")
    .insert({
      user_id: user.id,
      title: testTaskTitle,
      description: "Generated by Playwright E2E fixture",
      interval_value: 3,
      interval_unit: "days",
      preferred_day_of_week: null,
      next_due_date: formatIsoDate(2),
      last_action_date: null,
      last_action_type: null,
      ...overrides,
    })
    .select()
    .single();

  if (!createdTask || taskError) {
    throw new Error(`Unable to seed task for test: ${taskError?.message ?? "unknown error"}`);
  }

  return createdTask;
};

export const generateRandomTaskData = () => {
  const timestamp = Date.now();
  const intervalUnits = ["days", "weeks", "months"] as const;
  const randomUnit = intervalUnits[Math.floor(Math.random() * intervalUnits.length)];
  const randomValue = Math.floor(Math.random() * 10) + 1; // 1-10

  return {
    title: `Test Task ${timestamp}`,
    description: `Auto-generated test task created at ${new Date().toISOString()}`,
    intervalValue: randomValue,
    intervalUnit: randomUnit === "days" ? "Dni" : randomUnit === "weeks" ? "Tygodnie" : "Miesiące",
  };
};

export const findTaskByTitle = async (title: string, userId: string) => {
  const { data, error } = await supabaseAdmin
    .from("tasks")
    .select("*")
    .eq("user_id", userId)
    .eq("title", title)
    .single();

  if (error && error.code !== "PGRST116") {
    // PGRST116 is "not found" - that's ok for cleanup
    throw new Error(`Failed to find task: ${error.message}`);
  }

  return data;
};
